In [1]:
###创建数组（矩阵）
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array(range(1,6))
c = np.arange(1,6)
print(a, b, c)

print(type(a))
print(type(c))
print(c.dtype)
print("*"*30)
f=np.array([0.1,0.2,0.3])
print(f.dtype)

[1 2 3 4 5] [1 2 3 4 5] [1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int64
******************************
float64


In [110]:
###数据类型的操作
a= np.array([0,7,2,0], dtype=bool)
print(a.dtype)
print(a)
b=a.astype(np.int8)
print(b.dtype)

bool
[False  True  True False]
int8


In [111]:

help(a.astype)

Help on built-in function astype:

astype(...) method of numpy.ndarray instance
    a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
    
    Copy of the array, cast to a specified type.
    
    Parameters
    ----------
    dtype : str or dtype
        Typecode or data-type to which the array is cast.
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout order of the result.
        'C' means C order, 'F' means Fortran order, 'A'
        means 'F' order if all the arrays are Fortran contiguous,
        'C' order otherwise, and 'K' means as close to the
        order the array elements appear in memory as possible.
        Default is 'K'.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur. Defaults to 'unsafe'
        for backwards compatibility.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are al

In [12]:
b

array([1, 2, 3, 4, 5])

In [14]:
#数组的形状
a = np.array([[3,4,5,6,7,8], [1,2,3,4,5,6]])
a.shape

(2, 6)

In [16]:
a.reshape(4,3)

array([[3, 4, 5],
       [6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
t3 = np.array([[[1,2,3], [4,5,6],[7,8,9],[10,11,12]]])
t3.shape

#有返回值的方法，不会对数组本身进行修改。
t3.reshape(3,2,2)
t3
t3+2
t3*3

array([[[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27],
        [30, 33, 36]]])

In [32]:
a = np.arange(24)
print(a.shape)
a.reshape(4,2,3)
print(a.shape)

(24,)
(24,)


In [34]:
t3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:

t3.flatten().shapeo

(12,)

In [69]:
#数组和数组的计算
t5 = np.arange(0,24).reshape((4,6))

t6 = np.arange(100,124).reshape((4,6))
t5+t6
t5
t7 = np.arange(0,6)
t5-t7

array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [74]:
t8 = np.arange(0,4).reshape((4,1))
print(t8)
print(t5)
t5-t8

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20]])

In [98]:
#数组和数组计算
a = np.arange(0,27).reshape(3,3,3)
print(a)
b = np.arange(1,4).reshape((3,1))
print(b)
print(a-b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[1]
 [2]
 [3]]
[[[-1  0  1]
  [ 1  2  3]
  [ 3  4  5]]

 [[ 8  9 10]
  [10 11 12]
  [12 13 14]]

 [[17 18 19]
  [19 20 21]
  [21 22 23]]]


In [9]:
# 读取csv 文件
us_file_path = "./youtube_video_data/US_video_data_numbers.csv"
uk_file_path = "./youtube_video_data/GB_video_data_numbers.csv"

t1 = np.loadtxt(us_file_path, delimiter=",",dtype="int",unpack=True)
t1.shape

(4, 1688)

In [65]:
#数组转置
t1 = np.arange(24).reshape((4,6))
t1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [66]:
t1.transpose()
t1.T
t1.swapaxes(0,1)

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [67]:
t1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [86]:
#numpy 索引和切片
#取第1 和 4列
print(t1[:,[1,4]])

#取不连续多行
print(t1[[1,2,3]])

#取连续多行
print(t1[2:])

#取第1行到第3行，第3列到第5列
print(t1[1:3, 2:5])

[[ 1  4]
 [ 7 10]
 [13 16]
 [19 22]]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 8  9 10]
 [14 15 16]]


In [48]:
t1[:,[3,4]] = 0
t1

array([[ 0,  1,  2,  0,  0,  0],
       [ 6,  7,  8,  0,  0,  0],
       [12, 13, 14,  0,  0,  0],
       [18, 19, 20,  0,  0,  0]])

In [88]:
t = np.arange(0,24).reshape((4,6))
t

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [93]:
#numpy中布尔索引
t[t>18]=88
t

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 88, 88, 88, 88, 88]])

In [107]:
# numpy中三元运算符
t = np.arange(0,24).reshape((6,4))
print(t)
np.where(t<3, t, t*10)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[  0,   1,   2,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110],
       [120, 130, 140, 150],
       [160, 170, 180, 190],
       [200, 210, 220, 230]])

In [120]:
#数组的拼接
t1 = np.arange(0,12).reshape((2,6))
print(t1)
print("*"*30)
t2 = np.arange(12,24).reshape((2,6))
print(t2)
print("*"*30)

print(np.vstack((t1,t2)))
print("*"*30)
print(np.hstack((t1,t2)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
******************************
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
******************************
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
******************************
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


In [96]:
a = 10 if 3<2 else 20
a

20