In [298]:
###创建数组（矩阵）
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array(range(1,6))
c = np.arange(1,6)
print(a, b, c)

print(type(a))
print(type(c))
print(c.dtype)
print("*"*30)
f=np.array([0.1,0.2,0.3])
print(f.dtype)

[1 2 3 4 5] [1 2 3 4 5] [1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int64
******************************
float64


In [299]:
###数据类型的操作
a= np.array([0,7,2,0], dtype=bool)
print(a.dtype)
print(a)
b=a.astype(np.int8)
print(b.dtype)

bool
[False  True  True False]
int8


In [301]:
b

array([0, 1, 1, 0], dtype=int8)

In [302]:
#数组的形状
a = np.array([[3,4,5,6,7,8], [1,2,3,4,5,6]])
a.shape

(2, 6)

In [303]:
a.reshape(4,3)

array([[3, 4, 5],
       [6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [304]:
t3 = np.array([[[1,2,3], [4,5,6],[7,8,9],[10,11,12]]])
t3.shape

#有返回值的方法，不会对数组本身进行修改。
t3.reshape(3,2,2)
t3
t3+2
t3*3

array([[[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27],
        [30, 33, 36]]])

In [305]:
a = np.arange(24)
print(a.shape)
a.reshape(4,2,3)
print(a.shape)

(24,)
(24,)


In [306]:
t3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#数组和数组的计算
t5 = np.arange(0,24).reshape((4,6))

t6 = np.arange(100,124).reshape((4,6))
t5+t6
t5
t7 = np.arange(0,6)
t5-t7

In [ ]:
t8 = np.arange(0,4).reshape((4,1))
print(t8)
print(t5)
t5-t8

In [ ]:
#数组和数组计算
a = np.arange(0,27).reshape(3,3,3)
print(a)
b = np.arange(1,4).reshape((3,1))
print(b)
print(a-b)

In [340]:
# 读取csv 文件
us_file_path = "./youtube_video_data/US_video_data_numbers.csv"
uk_file_path = "./youtube_video_data/GB_video_data_numbers.csv"

us = np.loadtxt(us_file_path, delimiter=",",dtype="int")
uk = np.loadtxt(uk_file_path, delimiter=",",dtype="int")
#t1 = np.loadtxt(us_file_path, delimiter=",",dtype="int",unpack=True)

zeros = np.zeros((us.shape[0], 1))
ones = np.ones((uk.shape[0], 1))

us = np.hstack((us, zeros))
uk = np.hstack((uk, ones))

final_data = np.vstack((us, uk)).astype(int)
final_data

array([[4394029,  320053,    5931,   46245,       0],
       [7860119,  185853,   26679,       0,       0],
       [5845909,  576597,   39774,  170708,       0],
       ...,
       [ 109222,    4840,      35,     212,       1],
       [ 626223,   22962,     532,    1559,       1],
       [  99228,    1699,      23,     135,       1]])

In [333]:
us.shape
uk.shape
help(np.vstack)

Help on function vstack in module numpy:

vstack(tup)
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays, will be at least 2-D.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    hstack

In [ ]:
#数组转置
t1 = np.arange(24).reshape((4,6))
t1

In [ ]:
t1.transpose()
t1.T
t1.swapaxes(0,1)

In [ ]:
t1

In [423]:
#numpy 索引和切片
#取第1 和 4列
t1 = np.arange(0,24).reshape(4,6)
print(t1)
#print(t1[:,[1,4]])

#取不连续多行
print(t1[[1,3],:3])

#取连续多行
print(t1[2:])

#取第1行到第3行，第3列到第5列
print(t1[1:3, 2:5])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 6  7  8]
 [18 19 20]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 8  9 10]
 [14 15 16]]


In [ ]:
t1[:,[3,4]] = 0
t1

In [ ]:
t = np.arange(0,24).reshape((4,6))
t

In [ ]:
#numpy中布尔索引
t[t>18]=88
t

In [ ]:
# numpy中三元运算符
t = np.arange(0,24).reshape((6,4))
print(t)
np.where(t<3, t, t*10)

In [ ]:
#数组的拼接
t1 = np.arange(0,12).reshape((2,6))
print(t1)
print("*"*30)
t2 = np.arange(12,24).reshape((2,6))
print(t2)
print("*"*30)

# 竖直拼接 vertically
print(np.vstack((t1,t2)))
print("*"*30)
#水平拼接 horizontally
print(np.hstack((t1,t2)))

In [ ]:
t= np.ones((5,2)).astype(int)
#t = np.arange(0,24).reshape((6,4))
t[:,1] = 2
t[1,0] = 100
t
t2 = t.copy()
t2[2,1] = 100
t
t2

In [ ]:
t.mean()

In [ ]:
np.median(t)

In [ ]:
t.std()

In [ ]:
t2.std()

In [ ]:
t = np.eye(5)
t

In [ ]:
t[t==1] = -1
t

In [ ]:
t.argmax(axis=0)

In [ ]:
t = np.random.randn(40,30)
t

In [ ]:
print(t.mean(axis=None))
t.std()

In [ ]:
np.ones((2,3)).std()

In [ ]:
np.random.seed(10)

np.random.randint(10, 20, (4,4))

In [ ]:

np.random.seed(10)
np.random.randint(10, 20, (4,4))

In [385]:
a = list(range(10))
b=a[0:6]

In [398]:
t = np.arange(15).reshape(3,5).astype(float)
t[0, 2:] = np.nan
np.count_nonzero(t!=t)
t[t==t]
t[np.isnan(t)] = 99
t

array([[ 0.,  1., 99., 99., 99.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [379]:
t[t == 0] = 11
t
t = np.array([1, 20, 68, 1000, 10000, 10090])
t.mean()

3529.8333333333335

In [411]:
np.median(t)
for i in range(3):

0
1
2


In [413]:
def fill_ndarry_col(t):
    for i in range(t.shape[1]):  #iterate column
        temp_col = t[:,i]
        if np.count_nonzero(temp_col!=temp_col) != 0:
            mean_value = temp_col[temp_col==temp_col].mean()
            temp_col[np.isnan(temp_col)] = mean_value
    return t
            
t = np.arange(0,24,dtype=float).reshape((4,6))
t[2,0:3] = np.nan
print(t)
print(fill_ndarry_col(t))

 

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [nan nan nan 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [ 8.  9. 10. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [433]:
t = np.arange(0,24,dtype=float).reshape((4,6))
print(t)
t[:,0] == 0
t[t[:,0]!=0]



[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


array([[ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [428]:
10//3

3