In [134]:

from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler,StandardScaler, Imputer

import numpy as np
import jieba

In [2]:

d1 = [{'city': '北京','temperature':100},
{'city': '上海','temperature':60},
{'city': '深圳','temperature':30}]

#instantition
dict = DictVectorizer(sparse=False)
data = dict.fit_transform(d1)
#print(data)
data

dict.get_feature_names()

['city=上海', 'city=北京', 'city=深圳', 'temperature']

In [3]:
print(data)

[[  0.   1.   0. 100.]
 [  1.   0.   0.  60.]
 [  0.   0.   1.  30.]]


In [63]:
#对文本进行特征值化
cv = CountVectorizer()

l2 = ["life is is short,i like python",
"life is too long,i dislike python"]

data = cv.fit_transform(l2)
print(data)
print(cv.get_feature_names())

print(data.toarray())

  (0, 2)	1
  (0, 1)	2
  (0, 6)	1
  (0, 3)	1
  (0, 5)	1
  (1, 2)	1
  (1, 1)	1
  (1, 5)	1
  (1, 7)	1
  (1, 4)	1
  (1, 0)	1
['dislike', 'is', 'life', 'like', 'long', 'python', 'short', 'too']
[[0 2 1 1 0 1 1 0]
 [1 1 1 0 1 1 0 1]]


In [69]:
a = jieba.cut("我是一个屌丝")
a = list(a)
a

['我', '是', '一个', '屌丝']

In [29]:
b = ' '.join(a)
b

'我 是 一个 好 程序员'

In [74]:
# 中文特征值化
l1 = ["今天很残酷，明天更残酷，后天很美好，但绝对大部分是死在明天晚上，所以每个人不要放弃今天。",
     "我们看到的从很远星系来的光是在几百万年之前发出的，这样当我们看到宇宙时，我们是在看它的过去。",
     "如果只用一种方式了解某样事物，你就不会真正了解它。了解事物真正含义的秘密取决于如何将其与我们所了解的事物相联系。"]
range(len(l1))
c = []
for i in range(len(l1)):
     c.append(' '.join(jieba.cut(l1[i])))

len(c)

3

In [66]:
cv = CountVectorizer()
data = cv.fit_transform(c)
print(data.toarray())
print(cv.get_feature_names())

[[0 0 1 0 0 0 2 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 2 0 1 0 2 1 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 1 3 0 0 0 0 1 0 0 0 0 2 0 0 0 0 0 1 1]
 [1 1 0 0 4 3 0 0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 0 0 0 1 0 0 0 2 1 0 0 1 0 0]]
['一种', '不会', '不要', '之前', '了解', '事物', '今天', '光是在', '几百万年', '发出', '取决于', '只用', '后天', '含义', '大部分', '如何', '如果', '宇宙', '我们', '所以', '放弃', '方式', '明天', '星系', '晚上', '某样', '残酷', '每个', '看到', '真正', '秘密', '绝对', '美好', '联系', '过去', '这样']


In [105]:
import numpy as np
tf = TfidfVectorizer()
data = tf.fit_transform(c)
print(tf.get_feature_names())
print(data.toarray())

aa = data.toarray()[0]

np.argmax(aa)
names = tf.get_feature_names()
names[np.argmax(data.toarray()[2])]

['一种', '不会', '不要', '之前', '了解', '事物', '今天', '光是在', '几百万年', '发出', '取决于', '只用', '后天', '含义', '大部分', '如何', '如果', '宇宙', '我们', '所以', '放弃', '方式', '明天', '星系', '晚上', '某样', '残酷', '每个', '看到', '真正', '秘密', '绝对', '美好', '联系', '过去', '这样']
[[0.         0.         0.21821789 0.         0.         0.
  0.43643578 0.         0.         0.         0.         0.
  0.21821789 0.         0.21821789 0.         0.         0.
  0.         0.21821789 0.21821789 0.         0.43643578 0.
  0.21821789 0.         0.43643578 0.21821789 0.         0.
  0.         0.21821789 0.21821789 0.         0.         0.        ]
 [0.         0.         0.         0.2410822  0.         0.
  0.         0.2410822  0.2410822  0.2410822  0.         0.
  0.         0.         0.         0.         0.         0.2410822
  0.55004769 0.         0.         0.         0.         0.2410822
  0.         0.         0.         0.         0.48216441 0.
  0.         0.         0.         0.         0.2410822  0.2410822 ]
 [0.15698297 0.15698297 0.

'了解'

In [129]:
# 归一化
_x = [[90,2,10,40],[60,4,15,45],[75,3,13,46]]

mm = MinMaxScaler(feature_range=(2,3))
data = mm.fit_transform(_x)

print(data)


[[3.         2.         2.         2.        ]
 [2.         3.         3.         2.83333333]
 [2.5        2.5        2.6        3.        ]]


In [138]:
#缺失值

_x = [[1, 2], [np.nan, 3], [7, 6]]
print(_x)
im = Imputer(strategy='mean',axis=0)

data = im.fit_transform(_x)
data

[[1, 2], [nan, 3], [7, 6]]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[1., 2.],
       [4., 3.],
       [7., 6.]])

In [ ]:
#特征选择- 删除低方差的特征



