In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
import tensorflow.feature_column as fc

import os
import sys

import matplotlib.pyplot as plt
from IPython.display import clear_output

In [2]:
tf.enable_eager_execution()

In [3]:
! pip install requests

You should consider upgrading via the 'pip install --upgrade pip' command.


In [4]:
models_path = os.path.join(os.getcwd(), 'models')
sys.path.append(models_path)

In [5]:
from official.wide_deep import census_dataset
from official.wide_deep import census_main

census_dataset.download("/tmp/census_data/")

W0725 08:33:50.089238 140427323885376 deprecation_wrapper.py:119] From /tf/notebooks/tf_official/estimators/models/official/wide_deep/census_dataset.py:78: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0725 08:33:50.090740 140427323885376 deprecation_wrapper.py:119] From /tf/notebooks/tf_official/estimators/models/official/wide_deep/census_dataset.py:81: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

W0725 08:37:24.219202 140427323885376 deprecation_wrapper.py:119] From /tf/notebooks/tf_official/estimators/models/official/wide_deep/census_dataset.py:62: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

W0725 08:37:24.549461 140427323885376 deprecation_wrapper.py:119] From /tf/notebooks/tf_official/estimators/models/official/wide_deep/census_dataset.py:73: The name tf.gfile.Remove is deprecated. Please use tf.io.gfile.remove instead.



In [6]:
if "PYTHONPATH" in os.environ:
  os.environ['PYTHONPATH'] += os.pathsep +  models_path
else:
  os.environ['PYTHONPATH'] = models_path

In [9]:
!python -m official.wide_deep.census_main --help

W0725 08:40:17.243052 140126278432576 deprecation_wrapper.py:119] From /tf/notebooks/tf_official/estimators/models/official/wide_deep/census_main.py:114: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0725 08:40:17.243367 140126278432576 deprecation_wrapper.py:119] From /tf/notebooks/tf_official/estimators/models/official/wide_deep/census_main.py:114: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

Train DNN on census income dataset.
flags:

/tf/notebooks/tf_official/estimators/models/official/wide_deep/census_main.py:
  -bs,--batch_size:
    Batch size for training and evaluation. When using multiple gpus, this is
    the
    global batch size for all devices. For example, if the batch size is 32 and
    there are 4 GPUs, each GPU will get 8 examples on each step.
    (default: '40')
    (an integer)
  --[no]clean:
    If set, model_dir will be removed if it exists.
    (default: 'false')

In [10]:
!python -m official.wide_deep.census_main --model_type=wide --train_epochs=2

W0725 08:41:23.016214 140510523660096 deprecation_wrapper.py:119] From /tf/notebooks/tf_official/estimators/models/official/wide_deep/census_main.py:114: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0725 08:41:23.016488 140510523660096 deprecation_wrapper.py:119] From /tf/notebooks/tf_official/estimators/models/official/wide_deep/census_main.py:114: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0725 08:41:23.020954 140510523660096 deprecation_wrapper.py:119] From /tf/notebooks/tf_official/estimators/models/official/wide_deep/census_dataset.py:78: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0725 08:41:23.021172 140510523660096 deprecation_wrapper.py:119] From /tf/notebooks/tf_official/estimators/models/official/wide_deep/census_dataset.py:81: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

W0725 08:41:23.022311 14

I0725 08:41:29.788779 140510523660096 basic_session_run_hooks.py:692] global_step/sec: 324.217
I0725 08:41:29.789570 140510523660096 basic_session_run_hooks.py:260] average_loss = 0.32871822, loss = 13.148728 (0.309 sec)
I0725 08:41:29.789878 140510523660096 basic_session_run_hooks.py:260] loss = 13.148728, step = 501 (0.309 sec)
I0725 08:41:30.106144 140510523660096 basic_session_run_hooks.py:692] global_step/sec: 315.099
I0725 08:41:30.106930 140510523660096 basic_session_run_hooks.py:260] average_loss = 0.33019137, loss = 13.207655 (0.317 sec)
I0725 08:41:30.107261 140510523660096 basic_session_run_hooks.py:260] loss = 13.207655, step = 601 (0.317 sec)
I0725 08:41:30.416978 140510523660096 basic_session_run_hooks.py:692] global_step/sec: 321.708
I0725 08:41:30.417694 140510523660096 basic_session_run_hooks.py:260] average_loss = 0.40893573, loss = 16.35743 (0.311 sec)
I0725 08:41:30.417929 140510523660096 basic_session_run_hooks.py:260] loss = 16.35743, step = 701 (0.311 sec)
I0725 

In [11]:
!ls /tmp/census_data/

adult.data  adult.test


In [12]:
train_file = "/tmp/census_data/adult.data"
test_file = "/tmp/census_data/adult.test"

In [96]:
import pandas

train_df = pandas.read_csv(train_file, header=None, names=census_dataset._CSV_COLUMNS)
test_df = pandas.read_csv(test_file, header=None, names=census_dataset._CSV_COLUMNS)
census_dataset._CSV_COLUMNS

print(train_df.columns.size)
print(train_df.index.size)
train_df.head()
set(train_df['occupation'])

15
32561


{'?',
 'Adm-clerical',
 'Armed-Forces',
 'Craft-repair',
 'Exec-managerial',
 'Farming-fishing',
 'Handlers-cleaners',
 'Machine-op-inspct',
 'Other-service',
 'Priv-house-serv',
 'Prof-specialty',
 'Protective-serv',
 'Sales',
 'Tech-support',
 'Transport-moving'}

In [42]:
def easy_input_function(df, label_key, num_epochs, shuffle, batch_size):
    label = df[label_key]
    ds = tf.data.Dataset.from_tensor_slices((dict(df),label))
    
    if shuffle:
        ds = ds.shuffle(10000)
    ds = ds.batch(batch_size).repeat(num_epochs)
    
    return ds

In [67]:
ds = easy_input_function(train_df, label_key='income_bracket',
                        num_epochs=5,shuffle=True, batch_size=10)

for feature_batch,label_batch in ds.take(1):
    print('some feature keys:', list(feature_batch.keys()))
    print()
    print('A batch of Age:', feature_batch['age'])
    print()
    print('A batch of Label:', label_batch)



some feature keys: ['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'gender', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income_bracket']

A batch of Age: tf.Tensor([57 23 51 44 29 49 24 24 24 34], shape=(10,), dtype=int32)

A batch of Label: tf.Tensor(
[b'<=50K' b'<=50K' b'<=50K' b'<=50K' b'<=50K' b'>50K' b'<=50K' b'<=50K'
 b'<=50K' b'>50K'], shape=(10,), dtype=string)


In [68]:
import inspect
print(inspect.getsource(census_dataset.input_fn))

def input_fn(data_file, num_epochs, shuffle, batch_size):
  """Generate an input function for the Estimator."""
  assert tf.gfile.Exists(data_file), (
      '%s not found. Please make sure you have run census_dataset.py and '
      'set the --data_dir argument to the correct path.' % data_file)

  def parse_csv(value):
    tf.logging.info('Parsing {}'.format(data_file))
    columns = tf.decode_csv(value, record_defaults=_CSV_COLUMN_DEFAULTS)
    features = dict(zip(_CSV_COLUMNS, columns))
    labels = features.pop('income_bracket')
    classes = tf.equal(labels, '>50K')  # binary classification
    return features, classes

  # Extract lines from input files using the Dataset API.
  dataset = tf.data.TextLineDataset(data_file)

  if shuffle:
    dataset = dataset.shuffle(buffer_size=_NUM_EXAMPLES['train'])

  dataset = dataset.map(parse_csv, num_parallel_calls=5)

  # We call repeat after shuffling, rather than before, to prevent separate
  # epochs from blending together.
  dataset = 

In [72]:
ds = census_dataset.input_fn(train_file, num_epochs=5, shuffle=True, batch_size=10)

for feature_batch, label_batch in ds.take(1):
    print('Feature keys:', list(feature_batch.keys())[:5])
    print()
    print('Age batch:', feature_batch['age'])
    print()
    print('Label batch:', label_batch)

Feature keys: ['age', 'workclass', 'fnlwgt', 'education', 'education_num']

Age batch: tf.Tensor([67 18 30 35 20 42 38 48 29 49], shape=(10,), dtype=int32)

Label batch: tf.Tensor([False False False False False False  True False False False], shape=(10,), dtype=bool)


In [88]:
import functools

train_inpf = functools.partial(census_dataset.input_fn, train_file,
                              num_epochs=2, shuffle=True, batch_size=64)
test_inpf = functools.partial(census_dataset.input_fn, test_file,
                              num_epochs=1, shuffle=True, batch_size=64)
train_inpf
census_dataset.input_fn

<function official.wide_deep.census_dataset.input_fn(data_file, num_epochs, shuffle, batch_size)>

In [73]:
age = fc.numeric_column('age')
age

NumericColumn(key='age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)

In [74]:
fc.input_layer(feature_batch,[age]).numpy()

W0726 03:07:16.695712 140427323885376 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/feature_column/feature_column.py:205: NumericColumn._get_dense_tensor (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
W0726 03:07:16.697372 140427323885376 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/feature_column/feature_column.py:2115: NumericColumn._transform_feature (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
W0726 03:07:16.699953 140427323885376 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/feature_column/feature_c

array([[67.],
       [18.],
       [30.],
       [35.],
       [20.],
       [42.],
       [38.],
       [48.],
       [29.],
       [49.]], dtype=float32)

In [81]:
classifier = tf.estimator.LinearClassifier(feature_columns=[age])
classifier.train(train_inpf)
result= classifier.evaluate(test_inpf)
clear_output()
print(result)

{'accuracy': 0.76377374, 'accuracy_baseline': 0.76377374, 'auc': 0.6780343, 'auc_precision_recall': 0.3112702, 'average_loss': 0.5260417, 'label/mean': 0.23622628, 'loss': 33.586212, 'precision': 0.0, 'prediction/mean': 0.21324953, 'recall': 0.0, 'global_step': 1018}


In [83]:
education_num = tf.feature_column.numeric_column('education_num')
capital_gain = tf.feature_column.numeric_column('capital_gain')
capital_loss= tf.feature_column.numeric_column('capital_loss')
hours_per_week= tf.feature_column.numeric_column('hours_per_week')

my_numeric_columns = [age, education_num, capital_gain, \
                      capital_loss, hours_per_week]

fc.input_layer(feature_batch,my_numeric_columns).numpy()

array([[6.700e+01, 0.000e+00, 0.000e+00, 1.000e+01, 4.000e+01],
       [1.800e+01, 0.000e+00, 0.000e+00, 6.000e+00, 2.500e+01],
       [3.000e+01, 0.000e+00, 0.000e+00, 9.000e+00, 4.000e+01],
       [3.500e+01, 0.000e+00, 0.000e+00, 1.000e+01, 3.500e+01],
       [2.000e+01, 0.000e+00, 0.000e+00, 1.000e+01, 1.500e+01],
       [4.200e+01, 0.000e+00, 0.000e+00, 1.400e+01, 3.800e+01],
       [3.800e+01, 7.688e+03, 0.000e+00, 1.600e+01, 4.000e+01],
       [4.800e+01, 0.000e+00, 0.000e+00, 1.000e+01, 4.400e+01],
       [2.900e+01, 0.000e+00, 0.000e+00, 1.500e+01, 5.500e+01],
       [4.900e+01, 0.000e+00, 0.000e+00, 9.000e+00, 4.000e+01]],
      dtype=float32)

In [87]:
classifier = tf.estimator.LinearClassifier(feature_columns=my_numeric_columns)
classifier.train(train_inpf)

result = classifier.evaluate(test_inpf)

for key, value in sorted(result.items()):
    print('%s:%s'% (key,value))

W0726 03:41:49.784833 140427323885376 estimator.py:1811] Using temporary folder as model directory: /tmp/tmp2yn3zoia
W0726 03:41:56.426391 140427323885376 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.
W0726 03:41:56.454896 140427323885376 metrics_impl.py:804] Trapezoidal rule is known to produce incorrect PR-AUCs; please switch to "careful_interpolation" instead.


accuracy:0.7826301
accuracy_baseline:0.76377374
auc:0.71703655
auc_precision_recall:0.51337904
average_loss:1.2810885
global_step:1018
label/mean:0.23622628
loss:81.79373
precision:0.61619985
prediction/mean:0.24470079
recall:0.21164846


In [95]:

relationship = fc.categorical_column_with_vocabulary_list(
    'relationship',
    ['Husband',
     'Not-in-family',
     'Other-relative',
     'Own-child',
     'Unmarried',
     'Wife'])
relationship 
#fc.indicator_column(relationship)

VocabularyListCategoricalColumn(key='relationship', vocabulary_list=('Husband', 'Not-in-family', 'Other-relative', 'Own-child', 'Unmarried', 'Wife'), dtype=tf.string, default_value=-1, num_oov_buckets=0)

In [93]:
fc.input_layer(feature_batch, [age, fc.indicator_column(relationship)])


W0726 08:46:51.401709 140427323885376 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/feature_column/feature_column.py:205: IndicatorColumn._get_dense_tensor (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
W0726 08:46:51.403178 140427323885376 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/feature_column/feature_column.py:2115: IndicatorColumn._transform_feature (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
W0726 08:46:51.404257 140427323885376 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/feature_column/featu

<tf.Tensor: id=12524, shape=(10, 7), dtype=float32, numpy=
array([[67.,  1.,  0.,  0.,  0.,  0.,  0.],
       [18.,  0.,  0.,  0.,  1.,  0.,  0.],
       [30.,  1.,  0.,  0.,  0.,  0.,  0.],
       [35.,  0.,  1.,  0.,  0.,  0.,  0.],
       [20.,  0.,  0.,  0.,  1.,  0.,  0.],
       [42.,  0.,  1.,  0.,  0.,  0.,  0.],
       [38.,  0.,  0.,  0.,  0.,  0.,  1.],
       [48.,  0.,  0.,  0.,  0.,  1.,  0.],
       [29.,  0.,  1.,  0.,  0.,  0.,  0.],
       [49.,  1.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)>

In [98]:
occupation = tf.feature_column.categorical_column_with_hash_bucket(
    'occupation',hash_bucket_size=1000)
