In [60]:
import numpy as np
import tensorflow as tf

In [61]:
tf.enable_eager_execution()
tf.executing_eagerly()

True

In [62]:
a = tf.constant(2)
print(a)
print("a=%i" % a)

tf.Tensor(2, shape=(), dtype=int32)
a=2


In [63]:
print(a)

tf.Tensor(2, shape=(), dtype=int32)


In [64]:
a = tf.constant([[2,1],[1,0]], dtype=tf.float32)
print(a)
b = tf.constant([[3,0],[5,1]], dtype=tf.float32)
print(b)

print(a+b)
print(a*b)
print(tf.matmul(a,b))

tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3. 0.]
 [5. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[6. 0.]
 [5. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)


In [66]:
a = tf.constant([[2,1,2],[1,0,1]], dtype=tf.float32)
a.shape[1]
for i in range(a.shape[1]):
    for j in range(a.shape[0]):
        print(a[j][i])

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
