In [42]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.__version__

In [ ]:
g = tf.Graph()
print(g)
with g.as_default():
    c = tf.constant(11.0)
    print(c.graph)

In [ ]:
#加法
a = tf.constant(5.0)
b = tf.constant(6.0)

In [ ]:
print(a)

In [ ]:
sum1 = tf.add(a, b)

In [ ]:
print(sum1)

In [ ]:
# 默认的这张图，相当于是给程序分配一段内存
graph1= tf.get_default_graph()
print(graph1)

In [ ]:
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    print(sess.run(sum1))
    print(sum1.graph)
    print(c.graph)

In [ ]:
#placeholder是一个占位符，feed_dict是一个字典
i1 = tf.placeholder(tf.float32)
i2 = tf.placeholder(tf.float32)
o = tf.add(i1, i2)

with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    print(sess)
    print(sess.run(o, feed_dict={i1:10.0, i2:30}))
    print(o)


In [ ]:
print(i1)

In [ ]:
print(b)

In [ ]:
#创建随机值张量
z = tf.zeros([3,4], tf.float32)
isess = tf.InteractiveSession()
print(z.eval())

z.eval()
a = tf.constant(3.0)
print(a.eval())

isess.close()

tf.ones((3,4), tf.float32).eval()

#创建随机张量
b = tf.random_normal([4,4], mean=0, stddev=1,dtype=tf.float32)
b.eval()


c = tf.cast([[1,2,3],[4,5,6]],tf.float32)
c.name

In [ ]:
a = [[1,2,3],[4,5,6]]
b = [[7,8,9],[10,11,12]]

c= tf.concat([a,b],axis=0)
c.eval()
tf.cast(c,tf.float32).eval()

In [ ]:
# 变量OP
# 变量OP能够持久化保存，普通张量OP不能。
a = tf.constant([1,2,3,4,5])
var = tf.Variable(tf.random_normal([2,3],mean=0.0,stddev=1.0))
print(a, var)

# 必须做一步显示的初始化OP
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    #help(sess.run)
    #必须运行初始化OP
    sess.run(init_op)
    print(sess.run([a, var]))

In [ ]:
a =(5,) 
type(a)

In [ ]:
a = [10, 2,2,2,3,4,5,5,19]
b = tf.slice(a, [1], [8])

with tf.Session() as sess:
    print(b.eval())

In [ ]:
help(tf.slice)

In [ ]:

help(tf.reduce_mean)

In [ ]:
help(tf.matmul)

In [ ]:
a = [[1,1., 1], [1,2,3]]
b = [[3],[3.],[3]]
with tf.Session() as sess:
    print(tf.reduce_mean(a).eval())
    print(tf.square([2]).eval())
    print(tf.square([2,3]).eval())
    print(tf.matmul(a,b).eval())
    

In [41]:
a=[[1,2,13,4,5],[0,0,18,20,30]]
with tf.Session() as sess:
    print(tf.argmax(a,1).eval())
    print(tf.equal([1,2,4], [1,2,3]).eval())

[2 4]
[ True  True False]


In [54]:
a = np.arange(24).reshape(2,3,4)
print(a)
b = np.arange(24)
with tf.Session() as sess:
    print(tf.argmax(a,0).eval())
    print(tf.argmax(b,0).eval())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
23


In [55]:
help(tf.argmax)

Help on function argmax in module tensorflow.python.ops.math_ops:

argmax(input, axis=None, name=None, dimension=None, output_type=tf.int64)
    Returns the index with the largest value across axes of a tensor. (deprecated arguments)
    
    Instructions for updating:
    Use the `axis` argument instead
    
    Note that in case of ties the identity of the return value is not guaranteed.
    
    Usage:
      ```python
      import tensorflow as tf
      a = [1, 10, 26.9, 2.8, 166.32, 62.3]
      b = tf.math.argmax(input = a)
      c = tf.keras.backend.eval(b)
      # c = 4
      # here a[4] = 166.32 which is the largest element of a across axis 0
      ```
    
    Args:
      input: A `Tensor`. Must be one of the following types: `float32`, `float64`, `int32`, `uint8`, `int16`, `int8`, `complex64`, `int64`, `qint8`, `quint8`, `qint32`, `bfloat16`, `uint16`, `complex128`, `half`, `uint32`, `uint64`.
      axis: A `Tensor`. Must be one of the following types: `int32`, `int64`.
      

In [9]:
print( list(enumerate(list("ABCDE"))) )
print( dict((enumerate(list("ABCDE")))) )
a = dict(enumerate(list("ABCDE")))
a.keys()

[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E')]
{0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E'}


dict_keys([0, 1, 2, 3, 4])

In [27]:
a = list(range(1,5))
a
b = list("abcd")
b
dict(zip(b,a))

for i in zip(a,b):
    print(i)
    break

(1, 'a')


In [37]:
"A".encode("utf-8")
"A".encode("ascii")
a = b'abcd'
print(a)

for i in a.decode("utf-8"):
    print(i)

b'abcd'
a
b
c
d


In [40]:
i = b'b'
for j in i:
    print(j)

98
