In [9]:
import tensorflow as tf

In [2]:
tf.__version__

'1.14.0'

In [46]:
g = tf.Graph()
print(g)
with g.as_default():
    c = tf.constant(11.0)
    print(c.graph)

In [3]:
#加法
a = tf.constant(5.0)
b = tf.constant(6.0)

In [4]:
print(a)

Tensor("Const:0", shape=(), dtype=float32)


In [5]:
sum1 = tf.add(a, b)

In [6]:
print(sum1)

Tensor("Add:0", shape=(), dtype=float32)


In [8]:
# 默认的这张图，相当于是给程序分配一段内存
graph1= tf.get_default_graph()
print(graph1)

In [52]:
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    print(sess.run(sum1))
    print(sum1.graph)
    print(c.graph)

11.0


In [55]:
#placeholder是一个占位符，feed_dict是一个字典
i1 = tf.placeholder(tf.float32)
i2 = tf.placeholder(tf.float32)
o = tf.add(i1, i2)

with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    print(sess)
    print(sess.run(o, feed_dict={i1:10.0, i2:30}))
    print(o)


40.0
Tensor("Add_7:0", dtype=float32)


In [16]:
print(i1)

Tensor("Placeholder_6:0", dtype=float32)


In [18]:
print(b)

Tensor("Const_1:0", shape=(), dtype=float32)


In [68]:
#创建随机值张量
z = tf.zeros([3,4], tf.float32)
isess = tf.InteractiveSession()
print(z.eval())

z.eval()
a = tf.constant(3.0)
print(a.eval())

isess.close()

tf.ones((3,4), tf.float32).eval()

#创建随机张量
b = tf.random_normal([4,4], mean=0, stddev=1,dtype=tf.float32)
b.eval()


c = tf.cast([[1,2,3],[4,5,6]],tf.float32)
c.name

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
3.0


'Cast:0'

In [76]:
a = [[1,2,3],[4,5,6]]
b = [[7,8,9],[10,11,12]]

c= tf.concat([a,b],axis=0)
c.eval()
tf.cast(c,tf.float32).eval()

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [85]:
# 变量OP
# 变量OP能够持久化保存，普通张量OP不能。
a = tf.constant([1,2,3,4,5])
var = tf.Variable(tf.random_normal([2,3],mean=0.0,stddev=1.0))
print(a, var)

# 必须做一步显示的初始化OP
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    #help(sess.run)
    #必须运行初始化OP
    sess.run(init_op)
    print(sess.run([a, var]))

Tensor("Const_33:0", shape=(5,), dtype=int32) <tf.Variable 'Variable_8:0' shape=(2, 3) dtype=float32_ref>
[array([1, 2, 3, 4, 5], dtype=int32), array([[ 0.81836534, -0.53142774, -0.7248661 ],
       [ 0.10854868,  0.03093818,  0.3692326 ]], dtype=float32)]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
