In [3]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)

c = tf.multiply(a, b)
with tf.Session() as sess:
    print(sess.run(c, feed_dict={a:10, b:20}))

200


In [28]:
a = tf.placeholder(tf.int32, [None,None])
b = tf.placeholder(tf.int32, [None,None])

c = tf.matmul(a, b)

aa = np.arange(6.0).reshape([2,3])
print(aa)
bb = np.arange(6.0).reshape([3,2])
print(bb)

with tf.Session() as sess:
    print(sess.run(c, feed_dict={a:aa, b:bb}))
    print("a: " , sess.run(a, feed_dict={a:aa, b:bb}))
    
    cc = sess.run(c, feed_dict={a:aa, b:bb})
print(cc)

[[0. 1. 2.]
 [3. 4. 5.]]
[[0. 1.]
 [2. 3.]
 [4. 5.]]
[[10 13]
 [28 40]]
a:  [[0 1 2]
 [3 4 5]]
[[10 13]
 [28 40]]


numpy.ndarray

In [33]:
cc.mean(axis=1)

array([11.5, 34. ])

In [5]:
help(tf.placeholder)

Help on function placeholder in module tensorflow.python.ops.array_ops:

placeholder(dtype, shape=None, name=None)
    Inserts a placeholder for a tensor that will be always fed.
    
    **Important**: This tensor will produce an error if evaluated. Its value must
    be fed using the `feed_dict` optional argument to `Session.run()`,
    `Tensor.eval()`, or `Operation.run()`.
    
    For example:
    
    ```python
    x = tf.compat.v1.placeholder(tf.float32, shape=(1024, 1024))
    y = tf.matmul(x, x)
    
    with tf.compat.v1.Session() as sess:
      print(sess.run(y))  # ERROR: will fail because x was not fed.
    
      rand_array = np.random.rand(1024, 1024)
      print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.
    ```
    
    @compatibility(eager)
    Placeholders are not compatible with eager execution.
    @end_compatibility
    
    Args:
      dtype: The type of elements in the tensor to be fed.
      shape: The shape of the tensor to be fed (optional). If 