In [9]:
import tensorflow as tf
import numpy as np

In [ ]:
g = tf.Graph()
print(g)
with g.as_default():
    c = tf.constant(11.0)
    print(c.graph)

In [ ]:
with g.as_default():
    print(c.graph, c.name)
    a = tf.constant(2.0)
    assert c.graph is g
#     print(c.op)


In [ ]:
# 默认的这张图，相当于是给程序分配一段内存
graph1= tf.get_default_graph()
print(graph1)

In [ ]:
graph = tf.get_default_graph()
print(graph)

In [ ]:
#加法
a = tf.constant(5.0)
b = tf.constant(6.0)
sum1 = tf.add(a, b)
print(sum1)

plt = tf.placeholder(tf.float32, [2,3])
print(plt)

with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    print(sess.run(plt, feed_dict={plt:[[2,3,5],[1,2,3]]}))
    print(plt.shape)
    print(plt.graph)
    
    print("*"*10)
    print(sess.run(sum1))
    print(sum1.graph)
    print(c.graph)
    

In [ ]:
#形状的概念
# 静态形状
plt = tf.placeholder(tf.float32, [None, 3])
print(plt)
plt.set_shape([4,3])
print(plt)

# 静态形状只能设置一次
#plt.set_shape([5,2])
# print(plt)

#动态形状
plt_reshape = tf.reshape(plt, [2,3,2])
print(plt_reshape)


In [2]:
#变量op
# 变量OP能够持久化保存，普通张量OP不能。
a = tf.constant(3.0, name="a")
b = tf.constant(4.0, name="b")
c = tf.add(a,b, name="add")
var = tf.Variable(tf.random_normal([2,3], mean=0.0, stddev=1.0),name="variable_test")

print(a, var)
# 必须做一步显示的初始化op
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    # 必须运行初始化op
    sess.run(init_op)
    
    # 把程序的图结构写入事件文件，graph：把指定的图写进事件文件中
    filewriter= tf.summary.FileWriter("/tf/logs/test/", graph=sess.graph)
    
    print(sess.run([c, var]))

Tensor("a:0", shape=(), dtype=float32) <tf.Variable 'variable_test:0' shape=(2, 3) dtype=float32_ref>
[7.0, array([[-0.45653594,  1.8170266 , -0.03094544],
       [-1.3915446 , -0.750917  , -0.4406412 ]], dtype=float32)]


In [ ]:
#创建随机值张量
z = tf.zeros([3,4], tf.float32)
isess = tf.InteractiveSession()
print(z.eval())

z.eval()
a = tf.constant(3.0)
print(a.eval())

isess.close()

tf.ones((3,4), tf.float32).eval()

#创建随机张量
b = tf.random_normal([4,4], mean=0, stddev=1,dtype=tf.float32)
b.eval()


c = tf.cast([[1,2,3],[4,5,6]],tf.float32)
c.name

In [21]:
a = [1, 3, 5, 4] # (4,)
b = tf.one_hot(a, depth=6, on_value=1, axis=1) #(4, 6)

aa = [[1, 3, 5, 4],[0, 12, 2,3]] # (2,4)
#(2, 4, 26) 2个样本，每个样本4个目标值，每个目标值有26种可能性  
bb = tf.one_hot(aa, depth=26, on_value=1, axis=2) #(2, 4, 6) 
print(b)
print(bb)
with tf.Session() as sess:
    print(sess.run(b))
    print(sess.run(bb))

Tensor("one_hot_26:0", shape=(4, 6), dtype=int32)
Tensor("one_hot_27:0", shape=(2, 4, 26), dtype=int32)
[[0 1 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]]
[[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

 [[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]]


In [7]:
# tf.slice
a = list(range(12))
print(a)
b = tf.slice(a, [1], [8])
c = b[3:]
with tf.Session() as sess:
    print(b.eval())
    print(c.eval())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[1 2 3 4 5 6 7 8]
[4 5 6 7 8]


In [45]:
a=[[1,2,13,4,5],[0,0,18,20,30]]
b = np.arange(12).reshape(3,4)
c = np.arange(12).reshape(3,4)
c[2,2] = 0

equal_list = tf.cast(tf.equal(b,c), tf.int8)
print(equal_list)
el = tf.reduce_mean(equal_list, axis=1)
print(el)


print(b)
print(c)
with tf.Session() as sess:
    print(tf.argmax(a,1).eval())
    print(tf.equal([1,2,4], [1,2,3]).eval())
    print(tf.equal(b,c).eval())
    print(tf.reduce_mean(tf.cast(tf.equal(b,c), tf.float32)).eval())
    x = tf.cast(tf.equal(b,c), tf.float32)
    print(x.eval())
    xx = tf.reduce_mean(x, axis=1)
    print(xx)
    print(sess.run(tf.reduce_mean(x,axis=1)))
    print(tf.cast(xx, tf.int8).eval())
    print(
        sess.run(
            tf.reduce_mean(tf.cast(xx,tf.int8))
        )
    )

Tensor("Cast_42:0", shape=(3, 4), dtype=int8)
Tensor("Mean_44:0", shape=(3,), dtype=int8)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9  0 11]]
[2 4]
[ True  True False]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False  True]]
0.9166667
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 0. 1.]]
Tensor("Mean_46:0", shape=(3,), dtype=float32)
[1.   1.   0.75]
[1 1 0]
0


In [93]:
# tf.equal
# tf.reduce_mean
b = np.arange(12).reshape(3,4)
c = np.arange(12).reshape(3,4)
c[2,1] = 0
c[2,2] = 0
c[2,3] = 0
print(b)
equal_list = tf.cast(tf.equal(b,c), tf.int8)
print(equal_list)
el = tf.reduce_mean(tf.cast(tf.reduce_mean(equal_list, axis=1), tf.float32))
print(el)

rm = tf.reduce_mean(b.astype(float))
print(rm)

# print(b)
# print(c)
with tf.Session() as sess:
    print(sess.run(equal_list))
    print(sess.run(el))
    print(sess.run(rm))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Tensor("Cast_91:0", shape=(3, 4), dtype=int8)
Tensor("Mean_105:0", shape=(), dtype=float32)
Tensor("Mean_106:0", shape=(), dtype=float64)
[[1 1 1 1]
 [1 1 1 1]
 [1 0 0 0]]
0.6666667
5.5


In [53]:
a = np.arange(12)
print(a)
np.where(a < 6, a,10)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 0,  1,  2,  3,  4,  5, 10, 10, 10, 10, 10, 10])

In [69]:
# tf.ones_like
# tf.where
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
a = tf.ones_like(tensor)

one = tf.ones_like(tensor)
zero = tf.zeros_like(tensor)
b = tf.where(tensor <=5, x=one, y=zero)

# b = tf.where(tensor <=4, x=[[0,0,0],[9,9,9]], y=[[8,8,8],[1,1,1]])
with tf.Session() as sess:
    print(a.eval())
    print(b.eval())

[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 0]]


In [20]:
# tf.argmax
a=[[1,2,13,4,5],[0,0,18,20,30]]
with tf.Session() as sess:
    print(tf.argmax(a, axis=1).eval())

[2 4]


In [102]:
# tf.argmax
a = np.arange(24).reshape(2,3,4)
print(a)
b = np.arange(24)
with tf.Session() as sess:
    print(tf.argmax(a,1).eval())
    print(tf.argmax(b,0).eval())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[2 2 2 2]
 [2 2 2 2]]
23


In [ ]:
print( list(enumerate(list("ABCDE"))) )
print( dict((enumerate(list("ABCDE")))) )
a = dict(enumerate(list("ABCDE")))
a.keys()

In [ ]:
a = list(range(1,5))
a
b = list("abcd")
b
dict(zip(b,a))

for i in zip(a,b):
    print(i)
    break

In [96]:
"A".encode("utf-8")
"A".encode("ascii")
a = b'abcd'
print(a)

for i in a.decode("utf-8"):
    print(i)

b'abcd'
a
b
c
d


In [95]:
i = b'A'
for j in i:
    print(j)

65
